materia = str(input('ingresa materia a evaluar '))
n1 = float(input('ingrese su nota en participación '))
n2 = float(input('ingrese su primer nota parcial: '))
n3 = float(input('ingrese su segunda nota parcial: '))
n4 = float(input('ingrese su nota del examen final: '))
partic = (n1*0.1)
parcial1 = (n2*0.25)
parcial2 = (n3*0.25)
final = (n4*0.4)
promedio = (partic+parcial1+parcial2+final)
print('tu calificación final en el area de', materia, 'es: ', promedio)